const SoulGems = [{name: 'Grubsnitch Soul', description: 'Gradually recovers own HP.', image: 'item_495.xi.00.png'},
{name: 'Hungramps Soul', description: 'Gradually recovers own HP.', image: 'item_495.xi.00.png'},
{name: 'Pittapat Soul', description: 'Recovers own HP.', image: 'item_492.xi.00.png'},
{name: 'Hungorge Soul', description: 'Recovers own HP.', image: 'item_495.xi.00.png'},
{name: 'Master Oden Soul', description: 'Quickly recovers own HP.', image: 'item_492.xi.00.png'},
{name: 'Peppillon Soul', description: 'Quickly recovers own HP.', image: 'item_495.xi.00.png'},
{name: 'Kyryn Soul', description: 'Quickly recovers own HP.', image: 'item_495.xi.00.png'},
{name: 'Unikirin Soul', description: 'Quickly recovers own HP.', image: 'item_495.xi.00.png'},
{name: 'Tublappa Soul', description: 'Recovers HP when Inspirited by an enemy.', image: 'item_491.xi.00.png'},
{name: 'Furgus Soul', description: 'Recovers HP when Inspirited by an enemy.', image: 'item_497.xi.00.png'},
{name: 'Samureel Soul', description: 'Recovers a little HP when Loafing.', image: 'item_491.xi.00.png'},
{name: 'Walkappa Soul', description: 'Recovers a little HP when Loafing.', image: 'item_494.xi.00.png'},
{name: 'Chatalie Soul', description: 'Recovers a little HP when Loafing.', image: 'item_497.xi.00.png'},
{name: 'Nagatha Soul', description: 'Recovers a little HP when Loafing.', image: 'item_497.xi.00.png'},
{name: 'Time Keeler Soul', description: 'Recovers some HP when Loafing.', image: 'item_491.xi.00.png'},
{name: 'Chummer Soul', description: 'Recovers some HP when Loafing.', image: 'item_498.xi.00.png'},
{name: 'Robogramps Soul', description: 'Recovers HP once when close to defeat.', image: 'item_495.xi.00.png'},
{name: 'Dragon Lord Soul', description: 'Recovers HP once when close to defeat.', image: 'item_498.xi.00.png'},
{name: 'Azure Dragon Soul', description: 'Recovers HP once when close to defeat.', image: 'item_498.xi.00.png'},
{name: 'Wotchagot Soul', description: 'Absorbs a little HP when an attack is successful.', image: 'item_493.xi.00.png'},
{name: 'Negatibuzz Soul', description: 'Absorbs a little HP when an attack is successful.', image: 'item_496.xi.00.png'},
{name: 'Hidabat Soul', description: 'Absorbs a little HP when an attack is successful.', image: 'item_496.xi.00.png'},
{name: 'Rockabelly Soul', description: 'Absorbs a little HP when an attack is successful.', image: 'item_497.xi.00.png'},
{name: 'Moskevil Soul', description: 'Absorbs some HP when an attack is successful.', image: 'item_496.xi.00.png'},
{name: 'Scritchy Soul', description: 'Absorbs some HP when an attack is successful.', image: 'item_496.xi.00.png'},
{name: 'Abodabat Soul', description: 'Absorbs some HP when an attack is successful.', image: 'item_496.xi.00.png'},
{name: 'Grumples Soul', description: 'Absorbs some HP when an attack is successful.', image: 'item_497.xi.00.png'},
{name: 'Eterna Soul', description: 'Absorbs some HP when an attack is successful.', image: 'item_497.xi.00.png'},
{name: 'Dracunyan Soul', description: 'Absorbs a lot of HP when an attack is successful.', image: 'item_496.xi.00.png'},
{name: 'Everfore Soul', description: 'Absorbs a lot of HP when an attack is successful.', image: 'item_497.xi.00.png'},
{name: 'Baku Soul', description: 'Has slightly increased amount of HP drained.', image: 'item_494.xi.00.png'},
{name: 'Wydeawake Soul', description: 'Has slightly increased amount of HP drained.', image: 'item_496.xi.00.png'},
{name: 'Peckpocket Soul', description: 'Has slightly increased amount of HP drained.', image: 'item_497.xi.00.png'},
{name: 'Bakulia Soul', description: 'Has increased amount of own HP drained.', image: 'item_494.xi.00.png'},
{name: 'Belfree Soul', description: 'Has increased amount of own HP drained.', image: 'item_496.xi.00.png'},
{name: 'Insomni Soul', description: 'Has increased amount of own HP drained.', image: 'item_497.xi.00.png'},
{name: 'Sandi Soul', description: 'Has increased amount of own HP drained.', image: 'item_497.xi.00.png'},
{name: 'Pandle Soul', description: 'STR + 20.', image: 'item_491.xi.00.png'},
{name: 'Lie-in Soul', description: 'STR + 20.', image: 'item_491.xi.00.png'},
{name: 'Hissfit Soul', description: 'STR + 20.', image: 'item_491.xi.00.png'},
{name: 'Mochismo Soul', description: 'STR + 20.', image: 'item_491.xi.00.png'},
{name: 'Slicenrice Soul', description: 'STR + 20.', image: 'item_491.xi.00.png'},
{name: 'Undy Soul', description: 'STR + 30.', image: 'item_491.xi.00.png'},
{name: 'Tanbo Soul', description: 'STR + 30.', image: 'item_491.xi.00.png'},
{name: 'Helmsman Soul', description: 'STR + 30.', image: 'item_491.xi.00.png'},
{name: 'Zerberker Soul', description: 'STR + 40.', image: 'item_491.xi.00.png'},
{name: 'Reuknight Soul', description: 'STR + 40.', image: 'item_491.xi.00.png'},
{name: 'Snee Soul', description: 'STR + 40.', image: 'item_491.xi.00.png'},
{name: 'Kapunki Soul', description: 'STR + 40.', image: 'item_491.xi.00.png'},
{name: 'Snortlehog Soul', description: 'STR + 40.', image: 'item_491.xi.00.png'},
{name: 'Snartle Soul', description: 'STR + 45.', image: 'item_491.xi.00.png'},
{name: 'Corptain Soul', description: 'STR + 45.', image: 'item_491.xi.00.png'},
{name: 'Cruncha Soul', description: 'STR + 45.', image: 'item_491.xi.00.png'},
{name: 'Gilgaros Soul', description: 'STR + 45.', image: 'item_493.xi.00.png'},
{name: 'Watermelnyan Soul', description: 'STR + 45.', image: 'item_494.xi.00.png'},
{name: 'Carniboy Soul', description: 'Gets a small STR boost when front and center.', image: 'item_496.xi.00.png'},
{name: 'Hovernyan Soul', description: 'Gets a STR boost when front and center.', image: 'item_491.xi.00.png'},
{name: 'Apelican Soul', description: 'Gets a STR boost when front and center.', image: 'item_492.xi.00.png'},
{name: 'Slimamander Soul', description: 'Gets a STR boost when front and center.', image: 'item_496.xi.00.png'},
{name: 'Duchoo Soul', description: 'SPR + 20.', image: 'item_492.xi.00.png'},
{name: "D'wanna Soul", description: 'SPR + 20.', image: 'item_492.xi.00.png'},
{name: 'Wazzat Soul', description: 'SPR + 20.', image: 'item_492.xi.00.png'},
{name: 'Timidevil Soul', description: 'SPR + 20.', image: 'item_496.xi.00.png'},
{name: "N'more Soul", description: 'SPR + 30.', image: 'item_492.xi.00.png'},
{name: "Q'wit Soul", description: 'SPR + 30.', image: 'item_492.xi.00.png'},
{name: 'Illoo Soul', description: 'SPR + 30.', image: 'item_492.xi.00.png'},
{name: 'Robokoma Soul', description: 'SPR + 40.', image: 'item_494.xi.00.png'},
{name: 'Beelzebold Soul', description: 'SPR + 40.', image: 'item_496.xi.00.png'},
{name: 'Skreek Soul', description: 'SPR + 40.', image: 'item_497.xi.00.png'},
{name: 'Draaagin Soul', description: 'SPR + 40.', image: 'item_497.xi.00.png'},
{name: 'Flengu Soul', description: 'SPR + 45.', image: 'item_492.xi.00.png'},
{name: 'Kyubi Soul', description: 'SPR + 45.', image: 'item_492.xi.00.png'},
{name: 'Frostail Soul', description: 'SPR + 45.', image: 'item_492.xi.00.png'},
{name: "Ray O'Light Soul", description: 'Gets a small SPR boost when front and center.', image: 'item_495.xi.00.png'},
{name: 'Faux Kappa Soul', description: 'Gets a SPR boost when front and center.', image: 'item_494.xi.00.png'},
{name: 'Dummkap Soul', description: 'SPD + 20.', image: 'item_492.xi.00.png'},
{name: 'Leggly Soul', description: 'SPD + 20.', image: 'item_494.xi.00.png'},
{name: 'Komasan Soul', description: 'SPD + 20.', image: 'item_494.xi.00.png'},
{name: 'Panja Pupil Soul', description: 'SPD + 20.', image: 'item_494.xi.00.png'},
{name: 'Elloo Soul', description: 'SPD + 25.', image: 'item_492.xi.00.png'},
{name: 'Thornyan Soul', description: 'SPD + 25.', image: 'item_494.xi.00.png'},
{name: 'Pookivil Soul', description: 'SPD + 25.', image: 'item_494.xi.00.png'},
{name: "K'mon K'mon Soul", description: 'SPD + 25.', image: 'item_496.xi.00.png'},
{name: 'Komane Soul', description: 'SPD + 30.', image: 'item_494.xi.00.png'},
{name: 'Nekidspeed Soul', description: 'SPD + 30.', image: 'item_494.xi.00.png'},
{name: 'Frostina Soul', description: 'SPD + 30.', image: 'item_494.xi.00.png'},
{name: 'Panja Pro Soul', description: 'SPD + 30.', image: 'item_494.xi.00.png'},
{name: 'Gimme Soul', description: 'SPD + 30.', image: 'item_496.xi.00.png'},
{name: 'Blizzaria Soul', description: 'SPD + 35.', image: 'item_494.xi.00.png'},
{name: 'Damona Soul', description: 'SPD + 35.', image: 'item_494.xi.00.png'},
{name: 'Yoodoit Soul', description: 'Gets a small SPD boost when front and center.', image: 'item_496.xi.00.png'},
{name: 'Robbinyu Soul', description: 'Gets a small SPD boost when front and center.', image: 'item_497.xi.00.png'},
{name: 'Jetnyan Soul', description: 'Gets a SPD boost when front and center.', image: 'item_494.xi.00.png'},
{name: 'Kelpacabana Soul', description: 'Gets a SPD boost when front and center.', image: 'item_495.xi.00.png'},
{name: 'Dulluma Soul', description: 'DEF + 20', image: 'item_493.xi.00.png'},
{name: 'Noway Soul', description: 'DEF + 20', image: 'item_493.xi.00.png'},
{name: 'Heheheel Soul', description: 'DEF + 20', image: 'item_497.xi.00.png'},
{name: 'Croonger Soul', description: 'DEF + 20', image: 'item_497.xi.00.png'},
{name: 'Darumacho Soul', description: 'DEF + 30', image: 'item_493.xi.00.png'},
{name: 'Armsman Soul', description: 'DEF + 30', image: 'item_493.xi.00.png'},
{name: 'Dismarelda Soul', description: 'DEF + 30', image: 'item_497.xi.00.png'},
{name: 'Urnaconda Soul', description: 'DEF + 30', image: 'item_497.xi.00.png'},
{name: 'Pride Shrimp Soul', description: 'DEF + 40', image: 'item_493.xi.00.png'},
{name: 'Mistank Soul', description: 'DEF + 40', image: 'item_493.xi.00.png'},
{name: 'Impass Soul', description: 'DEF + 40', image: 'item_493.xi.00.png'},
{name: 'Swelton Soul', description: 'DEF + 40', image: 'item_493.xi.00.png'},
{name: 'Robonyan Soul', description: 'DEF + 45', image: 'item_493.xi.00.png'},
{name: 'Dromp Soul', description: 'DEF + 45', image: 'item_493.xi.00.png'},
{name: 'Toadal Dude Soul', description: 'DEF + 45', image: 'item_493.xi.00.png'},
{name: 'Uber Geeko Soul', description: 'DEF + 45', image: 'item_493.xi.00.png'},
{name: 'Shrook Soul', description: 'Gets a small DEF boost when front and center.', image: 'item_497.xi.00.png'},
{name: 'Kiwinyan Soul', description: 'Gets a DEF boost when front and center.', image: 'item_494.xi.00.png'},
{name: 'Papa Windbag Soul', description: 'Gets slight boost to stats when front and center.', image: 'item_497.xi.00.png'},
{name: 'Lafalotta Soul', description: 'Has slightly reduced chance of being inspirited..', image: 'item_492.xi.00.png'},
{name: 'Blips Soul', description: 'Has slightly reduced chance of being inspirited..', image: 'item_492.xi.00.png'},
{name: 'Enerfly Soul', description: 'Has slightly reduced chance of being inspirited..', image: 'item_495.xi.00.png'},
{name: 'Enefly Soul', description: 'Has slightly reduced chance of being inspirited..', image: 'item_495.xi.00.png'},
{name: 'Espy Soul', description: 'Has reduced chance of being inspirited.', image: 'item_492.xi.00.png'},
{name: 'Infour Soul', description: 'Has reduced chance of being inspirited.', image: 'item_492.xi.00.png'},
{name: 'Goruma Soul', description: 'Has reduced chance of being inspirited.', image: 'item_493.xi.00.png'},
{name: 'Spenp Soul', description: 'Has reduced chance of being inspirited.', image: 'item_497.xi.00.png'},
{name: 'Betterfly Soul', description: 'Has greatly reduced chance of being Inspirited.', image: 'item_495.xi.00.png'},
{name: 'Compunzer Soul', description: 'Has greatly reduced chance of being Inspirited.', image: 'item_497.xi.00.png'},
{name: 'Lamedian Soul', description: 'Has greatly reduced chance of being Inspirited.', image: 'item_497.xi.00.png'},
{name: 'Almi Soul', description: 'Has greatly reduced chance of being Inspirited.', image: 'item_497.xi.00.png'},
{name: 'Slurpent Soul', description: 'Has greatly reduced chance of being Inspirited.', image: 'item_497.xi.00.png'},
{name: 'Grapenyan Soul', description: 'More susceptible to being Inspirited.', image: 'item_494.xi.00.png'},
{name: 'Suspicioni Soul', description: 'More susceptible to being Inspirited.', image: 'item_496.xi.00.png'},
{name: 'Tantroni Soul', description: 'More susceptible to being Inspirited.', image: 'item_496.xi.00.png'},
{name: 'Tyrat Soul', description: 'More susceptible to being Inspirited.', image: 'item_496.xi.00.png'},
{name: 'Awevil Soul', description: 'More susceptible to being Inspirited.', image: 'item_496.xi.00.png'},
{name: 'Poofessor Soul', description: 'More susceptible to being Inspirited.', image: 'item_496.xi.00.png'},
{name: 'Statiking Soul', description: 'When Inspirited, positive effects last longer.', image: 'item_492.xi.00.png'},
{name: 'Wondernyan Soul', description: 'When Inspirited, positive effects last longer.', image: 'item_494.xi.00.png'},
{name: 'Lady Longnek Soul', description: 'When Inspirited, positive effects last longer.', image: 'item_497.xi.00.png'},
{name: 'Slumberhog Soul', description: "Gradually refills Yokai's own soul meter.", image: 'item_491.xi.00.png'},
{name: 'Jumbelina Soul', description: "Gradually refills Yokai's own soul meter.", image: 'item_494.xi.00.png'},
{name: 'Furdinand Soul', description: "Gradually refills Yokai's own soul meter.", image: 'item_497.xi.00.png'},
{name: 'Cheeksqueek Soul', description: "Gradually refills Yokai's own soul meter.", image: 'item_497.xi.00.png'},
{name: 'Venoct Soul', description: "Quickly refills Yokai's own soul meter.", image: 'item_497.xi.00.png'},
{name: 'Shadow Venoct Soul', description: "Quickly refills Yokai's own soul meter.", image: 'item_497.xi.00.png'},
{name: 'Contrarioni Soul', description: 'Own Soultimate Moves are slightly more powerful.', image: 'item_496.xi.00.png'},
{name: 'Baddinyan Soul', description: 'Own Soultimate Moves are more powerful.', image: 'item_494.xi.00.png'},
{name: 'Agon Soul', description: 'Own Soultimate Moves are more powerful.', image: 'item_496.xi.00.png'},
{name: 'Greesel Soul', description: 'Own Soultimate Moves are a lot more powerful.', image: 'item_496.xi.00.png'},
{name: 'Robodraggie Soul', description: 'Own Soultimate Moves are a lot more powerful.', image: 'item_497.xi.00.png'},
{name: 'Ben Tover Soul', description: 'More likely to dodge Soultimate Moves.', image: 'item_497.xi.00.png'},
{name: 'Darknyan Soul', description: 'More likely to dodge Soultimate Moves.', image: 'item_497.xi.00.png'},
{name: 'Daiz Soul', description: 'More likely to dodge Soultimate Moves.', image: 'item_497.xi.00.png'},
{name: 'Confuze Soul', description: 'More likely to dodge Soultimate Moves.', image: 'item_497.xi.00.png'},
{name: 'Cadin Soul', description: 'Slightly increases chance of dodging attacks.', image: 'item_494.xi.00.png'},
{name: 'Steppa Soul', description: 'Slightly increases chance of dodging attacks.', image: 'item_495.xi.00.png'},
{name: 'Wiglin Soul', description: 'Slightly increases chance of dodging attacks.', image: 'item_495.xi.00.png'},
{name: 'Dimmy Soul', description: 'Slightly increases chance of dodging attacks.', image: 'item_496.xi.00.png'},
{name: 'Cadable Soul', description: 'Increases chance of dodging attacks.', image: 'item_494.xi.00.png'},
{name: 'Predictabull Soul', description: 'Increases chance of dodging attacks.', image: 'item_495.xi.00.png'},
{name: 'Rhyth Soul', description: 'Increases chance of dodging attacks.', image: 'item_495.xi.00.png'},
{name: 'Blandon Soul', description: 'Increases chance of dodging attacks.', image: 'item_496.xi.00.png'},
{name: 'Master Nyada Soul', description: 'Greatly increases chance of dodging attacks.', image: 'item_494.xi.00.png'},
{name: 'Spoilerina Soul', description: 'Greatly increases chance of dodging attacks.', image: 'item_494.xi.00.png'},
{name: 'Nul Soul', description: 'Greatly increases chance of dodging attacks.', image: 'item_496.xi.00.png'},
{name: 'Neighfarious Soul', description: 'Greatly increases chance of dodging attacks.', image: 'item_496.xi.00.png'},
{name: 'Boyclops Soul', description: 'Slightly increases chance of successful attack.', image: 'item_494.xi.00.png'},
{name: 'Singcada Soul', description: 'Increases chance of successful attack.', image: 'item_494.xi.00.png'},
{name: 'Flumpy Soul', description: 'Increases chance of successful attack.', image: 'item_497.xi.00.png'},
{name: 'Cuttincheez Soul', description: 'Increases chance of successful attack.', image: 'item_497.xi.00.png'},
{name: 'Nird Soul', description: 'Greatly increases chance of successful attack.', image: 'item_496.xi.00.png'},
{name: 'Eyesoar Soul', description: 'Greatly increases chance of successful attack.', image: 'item_496.xi.00.png'},
{name: 'Eyellure Soul', description: 'Greatly increases chance of successful attack.', image: 'item_496.xi.00.png'},
{name: 'Terrorpotta Soul', description: 'Slightly increases chance of making a critical hit.', image: 'item_493.xi.00.png'},
{name: 'Lie-in Heart Soul', description: 'Increases chance of making a critical hit.', image: 'item_491.xi.00.png'},
{name: 'Chansin Soul', description: 'Increases chance of making a critical hit.', image: 'item_491.xi.00.png'},
{name: 'Sheen Soul', description: 'Increases chance of making a critical hit.', image: 'item_491.xi.00.png'},
{name: 'Gleam Soul', description: 'Greatly increases chance of making a critical hit.', image: 'item_491.xi.00.png'},
{name: 'Demuncher Soul', description: 'Greatly increases chance of making a critical hit.', image: 'item_491.xi.00.png'},
{name: 'Devourer Soul', description: 'Greatly increases chance of making a critical hit.', image: 'item_491.xi.00.png'},
{name: 'Shogunyan Soul', description: 'Power of critical attacks is high.', image: 'item_491.xi.00.png'},
{name: 'Jibakoma Soul', description: 'Power of critical attacks is high.', image: 'item_494.xi.00.png'},
{name: 'Ake Soul', description: 'Power of critical attacks is high.', image: 'item_496.xi.00.png'},
{name: 'Payn Soul', description: 'Power of critical attacks is high.', image: 'item_496.xi.00.png'},
{name: 'Count Cavity Soul', description: 'Power of critical attacks is high.', image: 'item_496.xi.00.png'},
{name: 'Benkei Soul', description: 'Attacks stronger after an enemy is defeated.', image: 'item_491.xi.00.png'},
{name: 'B3-NK1 Soul', description: 'Attacks stronger after an enemy is defeated.', image: 'item_491.xi.00.png'},
{name: 'Jibanyan Soul', description: 'Attacks stronger after an enemy is defeated.', image: 'item_494.xi.00.png'},
{name: 'Komashura Soul', description: 'Attacks stronger after an enemy is defeated.', image: 'item_492.xi.00.png'},
{name: 'Blazion Soul', description: 'Attacks stronger after an ally is defeated.', image: 'item_491.xi.00.png'},
{name: 'Quaken Soul', description: 'Attacks stronger after an ally is defeated.', image: 'item_491.xi.00.png'},
{name: 'Minochi Soul', description: 'Takes slightly less damage from Fire attacks.', image: 'item_491.xi.00.png'},
{name: 'Whateverest Soul', description: 'Takes slightly less damage from Fire attacks.', image: 'item_493.xi.00.png'},
{name: 'Dazzabel Soul', description: 'Takes slightly less damage from Fire attacks.', image: 'item_494.xi.00.png'},
{name: 'Casanono Soul', description: 'Takes less damage from Fire attacks.', image: 'item_492.xi.00.png'},
{name: 'Lava Lord Soul', description: 'Takes less damage from Fire attacks.', image: 'item_493.xi.00.png'},
{name: 'Rattelle Soul', description: 'Takes less damage from Fire attacks.', image: 'item_494.xi.00.png'},
{name: 'Flamurice Soul', description: 'Takes much less damage from Fire attacks.', image: 'item_491.xi.00.png'},
{name: 'Whatuption Soul', description: 'Takes much less damage from Fire attacks.', image: 'item_493.xi.00.png'},
{name: 'Swelterrier Soul', description: 'Takes much less damage from Fire attacks.', image: 'item_494.xi.00.png'},
{name: 'Strawbnyan Soul', description: 'Takes much less damage from Fire attacks.', image: 'item_494.xi.00.png'},
{name: 'Sproink Soul', description: 'Takes much less damage from Fire attacks.', image: 'item_497.xi.00.png'},
{name: 'Copperled Soul', description: 'Takes much less damage from Fire attacks.', image: 'item_497.xi.00.png'},
{name: 'Snotsolong Soul', description: 'Takes slightly less damage from Water attacks.', image: 'item_492.xi.00.png'},
{name: 'Drizzelda Soul', description: 'Takes slightly less damage from Water attacks.', image: 'item_494.xi.00.png'},
{name: 'Fishpicable Soul', description: 'Takes slightly less damage from Water attacks.', image: 'item_497.xi.00.png'},
{name: 'Touphant Soul', description: 'Takes less damage from Water attacks.', image: 'item_493.xi.00.png'},
{name: 'Skelebella Soul', description: 'Takes less damage from Water attacks.', image: 'item_494.xi.00.png'},
{name: 'Droplette Soul', description: 'Takes less damage from Water attacks.', image: 'item_497.xi.00.png'},
{name: 'Rageon Soul', description: 'Takes less damage from Water attacks.', image: 'item_497.xi.00.png'},
{name: 'Tunatic Soul', description: 'Takes less damage from Water attacks.', image: 'item_497.xi.00.png'},
{name: 'Appak Soul', description: 'Takes much less damage from Water attacks.', image: 'item_494.xi.00.png'},
{name: 'Supyo Soul', description: 'Takes much less damage from Water attacks.', image: 'item_494.xi.00.png'},
{name: 'Tigappa Soul', description: 'Takes much less damage from Water attacks.', image: 'item_494.xi.00.png'},
{name: 'Drizzle Soul', description: 'Takes much less damage from Water attacks.', image: 'item_497.xi.00.png'},
{name: 'No-Go Kart Soul', description: 'Takes slightly less damage from Earth attacks.', image: 'item_493.xi.00.png'},
{name: 'Sandmeh Soul', description: 'Takes slightly less damage from Earth attacks.', image: 'item_495.xi.00.png'},
{name: 'Danke Sand Soul', description: 'Takes slightly less damage from Earth attacks.', image: 'item_497.xi.00.png'},
{name: 'Bowminos Soul', description: 'Takes less damage from Earth attacks.', image: 'item_492.xi.00.png'},
{name: 'Mr. Sandmeh Soul', description: 'Takes less damage from Earth attacks.', image: 'item_495.xi.00.png'},
{name: 'Dubbles Soul', description: 'Takes less damage from Earth attacks.', image: 'item_495.xi.00.png'},
{name: 'Walldin Soul', description: 'Takes much less damage from Earth attacks.', image: 'item_493.xi.00.png'},
{name: 'Sir Berus Soul', description: 'Takes much less damage from Earth attacks.', image: 'item_497.xi.00.png'},
{name: 'Arachnus Soul', description: 'Takes much less damage from Earth attacks.', image: 'item_497.xi.00.png'},
{name: 'Arachnia Soul', description: 'Takes much less damage from Earth attacks.', image: 'item_497.xi.00.png'},
{name: 'No Sandkyu Soul', description: 'Takes much less damage from Earth attacks.', image: 'item_497.xi.00.png'},
{name: 'Signibble Soul', description: 'Takes slightly less damage from Lightning atttacks.', image: 'item_492.xi.00.png'},
{name: 'Zappary Soul', description: 'Takes slightly less damage from Lightning atttacks.', image: 'item_493.xi.00.png'},
{name: 'Signiton Soul', description: 'Takes less damage from Lightning atttacks.', image: 'item_492.xi.00.png'},
{name: 'Failian Soul', description: 'Takes less damage from Lightning atttacks.', image: 'item_492.xi.00.png'},
{name: 'Chymera Soul', description: 'Takes much less damage from Lightning atttacks.', image: 'item_492.xi.00.png'},
{name: 'Kingmera Soul', description: 'Takes much less damage from Lightning atttacks.', image: 'item_492.xi.00.png'},
{name: 'Frazzel Soul', description: 'Takes much less damage from Lightning atttacks.', image: 'item_493.xi.00.png'},
{name: 'Papa Bolt Soul', description: 'Takes much less damage from Lightning atttacks.', image: 'item_495.xi.00.png'},
{name: 'Count Zapaway Soul', description: 'Takes slightly less damage from Wind attacks.', image: 'item_496.xi.00.png'},
{name: 'Buhu Soul', description: 'Takes slightly less damage from Wind attacks.', image: 'item_497.xi.00.png'},
{name: 'Flushback Soul', description: 'Takes slightly less damage from Wind attacks.', image: 'item_497.xi.00.png'},
{name: 'Leadoni Soul', description: 'Takes less damage from Wind attacks.', image: 'item_496.xi.00.png'},
{name: 'Mynimo Soul', description: 'Takes less damage from Wind attacks.', image: 'item_496.xi.00.png'},
{name: 'Tengloom Soul', description: 'Takes less damage from Wind attacks.', image: 'item_496.xi.00.png'},
{name: 'Tengu Soul', description: 'Takes much less damage from Wind attacks.', image: 'item_492.xi.00.png'},
{name: 'Reversette Soul', description: 'Takes much less damage from Wind attacks.', image: 'item_495.xi.00.png'},
{name: 'Vacuumory Soul', description: 'Takes much less damage from Wind attacks.', image: 'item_497.xi.00.png'},
{name: 'Mimikin Soul', description: 'Takes slightly less damage from Ice attacks.', image: 'item_493.xi.00.png'},
{name: 'Pupsicle Soul', description: 'Takes slightly less damage from Ice attacks.', image: 'item_494.xi.00.png'},
{name: 'Squeeky Soul', description: 'Takes slightly less damage from Ice attacks.', image: 'item_497.xi.00.png'},
{name: 'Mad Mountain Soul', description: 'Takes less damage from Ice attacks.', image: 'item_493.xi.00.png'},
{name: 'Slush Soul', description: 'Takes less damage from Ice attacks.', image: 'item_497.xi.00.png'},
{name: 'Chilhuahua Soul', description: 'Takes much less damage from Ice attacks.', image: 'item_494.xi.00.png'},
{name: 'Alhail Soul', description: 'Takes much less damage from Ice attacks.', image: 'item_497.xi.00.png'},
{name: 'Castelius III Soul', description: 'Takes less damage from Earth and Wind attacks.', image: 'item_493.xi.00.png'},
{name: 'Castelius II Soul', description: 'Takes less damage from Ice or Fire attacks.', image: 'item_493.xi.00.png'},
{name: 'Castelius I Soul', description: 'Takes less damage from Lightning or Water attacks.', image: 'item_493.xi.00.png'},
{name: 'Castelius Max Soul', description: 'Takes less damage from Ice, Wind, and Water hits.', image: 'item_493.xi.00.png'},
{name: 'Faysoff Soul', description: 'Takes less damage from all elemental attacks.', image: 'item_492.xi.00.png'},
{name: 'Goldenyan Soul', description: 'Takes less damage from all elemental attacks.', image: 'item_493.xi.00.png'},
{name: 'SV Snaggerjag Soul', description: 'Takes less damage from all elemental attacks.', image: 'item_497.xi.00.png'},
{name: 'Sushiyama Soul', description: "Enemies' guard becomes a little less effective.", image: 'item_491.xi.00.png'},
{name: 'Rhinoggin Soul', description: "Enemies' guard becomes a little less effective.", image: 'item_493.xi.00.png'},
{name: 'Grumpus Khan Soul', description: "Enemies' guard becomes a little less effective.", image: 'item_496.xi.00.png'},
{name: 'Groupus Khan Soul', description: "Enemies' guard becomes a little less effective.", image: 'item_496.xi.00.png'},
{name: 'Cricky Soul', description: "Enemies' guard becomes a little less effective.", image: 'item_497.xi.00.png'},
{name: 'Rhinormous Soul', description: "Enemies' guard becomes less effective.", image: 'item_493.xi.00.png'},
{name: 'Hornaplenty Soul', description: "Enemies' guard becomes less effective.", image: 'item_493.xi.00.png'},
{name: 'Robokapp Soul', description: "Enemies' guard becomes less effective.", image: 'item_494.xi.00.png'},
{name: 'Rawry Soul', description: "Enemies' guard becomes less effective.", image: 'item_497.xi.00.png'},
{name: 'Sumodon Soul', description: 'Withstand one K.O.', image: 'item_493.xi.00.png'},
{name: 'Yokozudon Soul', description: 'Withstand one K.O.', image: 'item_493.xi.00.png'},
{name: 'Machonyan Soul', description: 'Withstand one K.O.', image: 'item_491.xi.00.png'},
{name: 'Tattletell Soul', description: "Gradually recovers adjacent allies' HP.", image: 'item_492.xi.00.png'},
{name: 'Tongus Soul', description: "Gradually recovers adjacent allies' HP.", image: 'item_495.xi.00.png'},
{name: 'Happierre Soul', description: "Gradually recovers adjacent allies' HP.", image: 'item_495.xi.00.png'},
{name: 'Happycane Soul', description: "Gradually recovers adjacent allies' HP.", image: 'item_495.xi.00.png'},
{name: 'Tattlecast Soul', description: "Recovers adjacent allies' HP.", image: 'item_492.xi.00.png'},
{name: 'Skranny Soul', description: "Recovers adjacent allies' HP.", image: 'item_492.xi.00.png'},
{name: 'Verygoodsir Soul', description: "Recovers adjacent allies' HP.", image: 'item_492.xi.00.png'},
{name: 'Reversa Soul', description: "Recovers adjacent allies' HP.", image: 'item_495.xi.00.png'},
{name: "Ol' Saint Trick Soul", description: "Recovers adjacent allies' HP.", image: 'item_495.xi.00.png'},
{name: 'Sailornyan Soul', description: "Quickly recovers adjacent allies' HP.", image: 'item_494.xi.00.png'},
{name: 'Nurse Tongus Soul', description: "Quickly recovers adjacent allies' HP.", image: 'item_495.xi.00.png'},
{name: 'Mama Aura Soul', description: "Quickly recovers adjacent allies' HP.", image: 'item_495.xi.00.png'},
{name: 'Auntie Heart Soul', description: "Quickly recovers adjacent allies' HP.", image: 'item_495.xi.00.png'},
{name: 'Elder Bloom Soul', description: "Quickly recovers adjacent allies' HP.", image: 'item_495.xi.00.png'},
{name: 'Starrycane Soul', description: "Quickly recovers adjacent allies' HP.", image: 'item_495.xi.00.png'},
{name: 'Brushido Soul', description: 'When defeated, all Yokai in front will recover little HP.', image: 'item_491.xi.00.png'},
{name: 'Swosh Soul', description: 'When defeated, all Yokai in front will recover HP.', image: 'item_493.xi.00.png'},
{name: 'Melonyan Soul', description: 'When defeated, all Yokai in front will recover HP.', image: 'item_494.xi.00.png'},
{name: 'Snobetty Soul', description: 'Drains some HP from all adjacent Yokai.', image: 'item_496.xi.00.png'},
{name: 'Foiletta Soul', description: 'Drains some HP from all adjacent Yokai.', image: 'item_497.xi.00.png'},
{name: 'Allnyta Soul', description: 'Drains some HP from all adjacent Yokai.', image: 'item_496.xi.00.png'},
{name: 'Sgt. Burly Soul', description: 'Adjacent Yokai get a slight STR boost.', image: 'item_491.xi.00.png'},
{name: 'Manjimutt Soul', description: 'Adjacent Yokai get a slight STR boost.', image: 'item_497.xi.00.png'},
{name: 'Uncle Infinite Soul', description: 'Adjacent Yokai get a STR boost.', image: 'item_495.xi.00.png'},
{name: 'Multimutt Soul', description: 'Adjacent Yokai get a STR boost.', image: 'item_497.xi.00.png'},
{name: 'So-Sorree Soul', description: 'Adjacent Yokai get a slight SPR boost.', image: 'item_492.xi.00.png'},
{name: 'Nosirs Soul', description: 'Adjacent Yokai get a slight SPR boost.', image: 'item_497.xi.00.png'},
{name: 'Houzzat Soul', description: 'Adjacent Yokai get a SPR boost.', image: 'item_492.xi.00.png'},
{name: 'Brokenbrella Soul', description: 'Adjacent Yokai get a slight SPD boost.', image: 'item_492.xi.00.png'},
{name: 'Komajiro Soul', description: 'Adjacent Yokai get a slight SPD boost.', image: 'item_494.xi.00.png'},
{name: 'Komiger Soul', description: 'Adjacent Yokai get a SPD boost.', image: 'item_494.xi.00.png'},
{name: 'Rollen Soul', description: 'Adjacent Yokai get a slight DEF boost.', image: 'item_495.xi.00.png'},
{name: 'Toiletta Soul', description: 'Adjacent Yokai get a slight DEF boost.', image: 'item_497.xi.00.png'},
{name: 'Snaggly Soul', description: 'Adjacent Yokai get a slight DEF boost.', image: 'item_497.xi.00.png'},
{name: 'Whinona Soul', description: 'Adjacent Yokai get a DEF boost.', image: 'item_497.xi.00.png'},
{name: 'Don Chan Soul', description: 'Adjacent Yokai get a slight boost to all stats.', image: 'item_495.xi.00.png'},
{name: 'Mermaidyn Soul', description: 'Adjacent Yokai get a slight boost to all stats.', image: 'item_497.xi.00.png'},
{name: 'Mermadonna Soul', description: "Boost All Stats for Adjacent Allies'.", image: 'item_497.xi.00.png'},
{name: 'Mermother Soul', description: "Boost All Stats for Adjacent Allies'.", image: 'item_497.xi.00.png'},
{name: 'Smogling Soul', description: "Gradually recovers adjacent allies' Soul.", image: 'item_492.xi.00.png'},
{name: 'Alloo Soul', description: "Gradually recovers adjacent allies' Soul.", image: 'item_492.xi.00.png'},
{name: "Ol' Fortune Soul", description: "Gradually recovers adjacent allies' Soul.", image: 'item_495.xi.00.png'},
{name: 'Smogmella Soul', description: "Recovers adjacent allies' Soul.", image: 'item_492.xi.00.png'},
{name: 'Washogun Soul', description: "Recovers adjacent allies' Soul.", image: 'item_491.xi.00.png'},
{name: 'Oranyan Soul', description: "Recovers adjacent allies' Soul.", image: 'item_494.xi.00.png'},
{name: 'Fidgephant Soul', description: "Quickly recovers adjacent allies' Soul.", image: 'item_493.xi.00.png'},
{name: 'Enduriphant Soul', description: "Quickly recovers adjacent allies' Soul.", image: 'item_493.xi.00.png'},
{name: 'Blowkade Soul', description: "Quickly recovers adjacent allies' Soul.", image: 'item_493.xi.00.png'},
{name: 'Beetler Soul', description: 'All allies are less likely to loaf.', image: 'item_491.xi.00.png'},
{name: 'Beetall Soul', description: 'All allies are less likely to loaf.', image: 'item_491.xi.00.png'},
{name: 'Herbiboy Soul', description: 'All allies are less likely to loaf.', image: 'item_496.xi.00.png'},
{name: 'Cutta-nah Soul', description: 'Sends back a little damage to enemy.', image: 'item_491.xi.00.png'},
{name: 'Roughraff Soul', description: 'Sends back a little damage to enemy.', image: 'item_493.xi.00.png'},
{name: 'Ledballoon Soul', description: 'Sends back a little damage to enemy.', image: 'item_493.xi.00.png'},
{name: 'Coughkoff Soul', description: 'Sends back a little damage to enemy.', image: 'item_497.xi.00.png'},
{name: 'Hurchin Soul', description: 'Sends back a little damage to enemy.', image: 'item_497.xi.00.png'},
{name: 'Takoyakid Soul', description: 'Sends back a little damage to enemy.', image: 'item_497.xi.00.png'},
{name: 'Cutta-nah-nah Soul', description: 'Sends back some damage to enemy.', image: 'item_491.xi.00.png'},
{name: 'Slacka-slash Soul', description: 'Sends back some damage to enemy.', image: 'item_491.xi.00.png'},
{name: 'Badude Soul', description: 'Sends back some damage to enemy.', image: 'item_493.xi.00.png'},
{name: 'Bruff Soul', description: 'Sends back some damage to enemy.', image: 'item_493.xi.00.png'},
{name: 'Takoyaking Soul', description: 'Sends back some damage to enemy.', image: 'item_497.xi.00.png'},
{name: 'Mirapo Soul', description: 'Sends back a little damage from skill attack to enemy.', image: 'item_492.xi.00.png'},
{name: 'Mircle Soul', description: 'Sends back a little damage from skill attack to enemy.', image: 'item_492.xi.00.png'},
{name: 'Pallysol Soul', description: 'Sends back a little damage from skill attack to enemy.', image: 'item_495.xi.00.png'},
{name: 'Negasus Soul', description: 'Sends back a little damage from skill attack to enemy.', image: 'item_496.xi.00.png'},
{name: 'Miradox Soul', description: 'Sends back some damage from skill attack to enemy.', image: 'item_492.xi.00.png'},
{name: 'Scarasol Soul', description: 'Sends back some damage from skill attack to enemy.', image: 'item_495.xi.00.png'},
{name: 'Mudmunch Soul', description: 'When defeated, the enemy takes a little damage.', image: 'item_491.xi.00.png'},
{name: 'Grainpa Soul', description: 'When defeated, the enemy takes a little damage.', image: 'item_495.xi.00.png'},
{name: 'Irewig Soul', description: 'When defeated, the enemy takes a little damage.', image: 'item_497.xi.00.png'},
{name: 'Siro Soul', description: 'When defeated, the enemy takes damage.', image: 'item_491.xi.00.png'},
{name: 'Wobblewok Soul', description: 'When defeated, the enemy takes damage.', image: 'item_496.xi.00.png'},
{name: 'Robomutt Soul', description: 'When defeated, the enemy takes damage.', image: 'item_497.xi.00.png'},
{name: 'Firewig Soul', description: 'When defeated, the enemy takes damage.', image: 'item_497.xi.00.png'},
{name: 'Robonyan F Soul', description: 'Counterattack the enemy while Guarding.', image: 'item_493.xi.00.png'},
{name: 'Whapir Soul', description: 'Recieve a little more money after a battle.', image: 'item_494.xi.00.png'},
{name: 'Lodo Soul', description: 'Recieve a little more money after a battle.', image: 'item_495.xi.00.png'},
{name: 'Gnomey Soul', description: 'Recieve a little more money after a battle.', image: 'item_495.xi.00.png'},
{name: 'Chippa Soul', description: 'Receive more money after a battle.', image: 'item_495.xi.00.png'},
{name: 'Gush Soul', description: 'Receive more money after a battle.', image: 'item_497.xi.00.png'},
{name: 'Noko Soul', description: 'Receive more money after a battle.', image: 'item_497.xi.00.png'},
{name: 'High Gnomey Soul', description: 'Receive much more money after a battle.', image: 'item_495.xi.00.png'},
{name: 'Bloominoko Soul', description: 'Receive much more money after a battle.', image: 'item_497.xi.00.png'},
{name: 'Robonoko Soul', description: 'Receive much more money after a battle.', image: 'item_497.xi.00.png'},
{name: 'Cupistol Soul', description: 'Get a few more experience points after a battle.', image: 'item_492.xi.00.png'},
{name: 'Shmoopie Soul', description: 'Get a few more experience points after a battle.', image: 'item_494.xi.00.png'},
{name: 'Draggie Soul', description: 'Get a few more experience points after a battle.', image: 'item_497.xi.00.png'},
{name: 'Casanuva Soul', description: 'Receive more experience points after a battle.', image: 'item_492.xi.00.png'},
{name: 'Pinkipoo Soul', description: 'Receive more experience points after a battle.', image: 'item_494.xi.00.png'},
{name: 'Harry Barry Soul', description: 'Receive more experience points after a battle.', image: 'item_494.xi.00.png'},
{name: 'Supoor Hero Soul', description: 'Receive more experience points after a battle.', image: 'item_495.xi.00.png'},
{name: 'Smashibull Soul', description: 'Get way more experience points after a battle.', image: 'item_495.xi.00.png'},
{name: 'Dandoodle Soul', description: 'Get way more experience points after a battle.', image: 'item_497.xi.00.png'},
{name: 'Pandanoko Soul', description: 'Get way more experience points after a battle.', image: 'item_497.xi.00.png'},
{name: 'Wantston Soul', description: "Slightly ups enemies' likelihood to drop items.", image: 'item_495.xi.00.png'},
{name: 'Yoink Soul', description: "Slightly ups enemies' likelihood to drop items.", image: 'item_496.xi.00.png'},
{name: 'Babblong Soul', description: "Ups enemies' likelihood to drop items.", image: 'item_497.xi.00.png'},
{name: 'Buchinyan Soul', description: "Greatly ups enemies' likelihood to drop items.", image: 'item_494.xi.00.png'},
{name: 'Bananose Soul', description: "Greatly ups enemies' likelihood to drop items.", image: 'item_497.xi.00.png'},
{name: 'Cynake Soul', description: "Greatly ups enemies' likelihood to drop items.", image: 'item_497.xi.00.png'},
{name: 'Slitheref Soul', description: "Greatly ups enemies' likelihood to drop items.", image: 'item_497.xi.00.png'},
{name: 'Unfairy Soul', description: 'More susceptible to being Inspirited.', image: 'item_499.xi.00.png'},
{name: 'Unkaind Soul', description: 'Drains some HP from all adjacent Yokai.', image: 'item_499.xi.00.png'},
{name: 'Untidy Soul', description: 'DEF +45', image: 'item_499.xi.00.png'},
{name: 'Unpleasant Soul', description: 'Has increased amount of own HP drained.', image: 'item_499.xi.00.png'},
{name: 'Unkeen Soul', description: 'STR +45', image: 'item_499.xi.00.png'},
{name: 'Grublappa Soul', description: 'Recovers HP while Inspirited.', image: 'item_499.xi.00.png'},
{name: 'Madmunch Soul', description: 'When defeated, the enemy takes damage.', image: 'item_499.xi.00.png'},
{name: 'Badsmella Soul', description: "Refills Adjacent Allies' Soul Meter.", image: 'item_499.xi.00.png'},
{name: 'Mad Kappa Soul', description: 'Increases the SPR stat when in the middle spot while in battle.', image: 'item_499.xi.00.png'},
{name: 'Shamasol Soul', description: 'Technique countering on the enemy.', image: 'item_499.xi.00.png'},
{name: 'Gnomine Soul', description: 'Increases the Earned Money after end of a battle.', image: 'item_499.xi.00.png'},
{name: 'Defectabull Soul', description: 'Raises Evasiveness.', image: 'item_499.xi.00.png'},
{name: 'Feargus Soul', description: 'Recovers HP while Inspirited.', image: 'item_499.xi.00.png'},
{name: 'Scaremaiden Soul', description: "Boost All Stats for Adjacent Allies'", image: 'item_499.xi.00.png'},
{name: 'Wrongnek Soul', description: 'Extends the turns of good Inspirits for yourself.', image: 'item_499.xi.00.png'},
{name: 'Supernatural Soul', description: 'Inspirit always succeeds.', image: 'item_503.xi.00.png'},
{name: 'Stealth Soul', description: ' Cannot be targeted by enemies', image: 'item_503.xi.00.png'},
{name: 'Stinging Soul', description: 'Becomes possible to be targeted by enemies', image: 'item_503.xi.00.png'},
{name: 'Speed Soul', description: 'Gets one preemptive attack', image: 'item_500.xi.00.png'},
{name: 'Scatter Soul', description: "Holder's attacks pierce resistances.", image: 'item_500.xi.00.png'},
{name: 'Stubborn Soul', description: 'Becomes unable to do anything but guard.', image: 'item_501.xi.00.png'},
{name: 'Stout Soul', description: ' Increase effectiveness of Guarding.', image: 'item_501.xi.00.png'},
{name: 'Guarding Soul', description: 'Holder will Guard when moving to the front.', image: 'item_501.xi.00.png'},
{name: 'Slippery Soul', description: 'Increases time to spin Yokai wheel', image: 'item_503.xi.00.png'},
{name: 'Surly Soul', description: ' Makes it difficult for enemies to be purified.', image: 'item_503.xi.00.png'},
{name: 'Superstar Soul', description: 'Improves chances of befriending an enemy.', image: 'item_503.xi.00.png'},
{name: 'Sinister Soul', description: 'All healing Techniques will be weaker.', image: 'item_503.xi.00.png'},
{name: 'Surrender Soul', description: 'All elemental abilities become neutral.', image: 'item_503.xi.00.png'},
{name: 'Soldier Soul', description: 'No Yo-Kai will loaf around.', image: 'item_503.xi.00.png'},
{name: "Summoner's Soul", description: 'Will make wisps appear more often.', image: 'item_503.xi.00.png'},
{name: 'Searing Soul', description: 'Gives Fire-attribute damage to normal attacks.', image: 'item_502.xi.00.png'},
{name: 'Sodden Soul', description: 'Gives Water-attribute damage to normal attacks.', image: 'item_502.xi.00.png'},
{name: 'Snow Soul', description: 'Gives Ice-attribute damage to normal attacks.', image: 'item_502.xi.00.png'},
{name: 'Storm Soul', description: 'Gives Lightning-attribute damage to normal attacks.', image: 'item_502.xi.00.png'},
{name: 'Squall Soul', description: 'Gives Wind-attribute damage to normal attacks.', image: 'item_502.xi.00.png'},
{name: 'Sprouting Soul', description: 'Gives Earth-attribute damage to normal attacks.', image: 'item_502.xi.00.png'},
{name: 'Scorching Soul', description: "Changes holder's current Technique to Incinerate.", image: 'item_500.xi.00.png'},
{name: 'Soaking Soul', description: "Changes holder's current Technique to Waterfall.", image: 'item_500.xi.00.png'},
{name: 'Subzero Soul', description: "Changes holder's current Technique to Blizzard.", image: 'item_500.xi.00.png'},
{name: 'Spin Soul', description: "Changes holder's current Technique to Storm.", image: 'item_500.xi.00.png'},
{name: 'Spacedust Soul', description: "Changes holder's current Technique to Meteor.", image: 'item_500.xi.00.png'},
{name: 'Sparking Soul', description: "Changes holder's current Technique to Voltage.", image: 'item_500.xi.00.png'}
]