window.randomAttitudeDatabase=[
    {
        "CharaRandomActType": 1,
        "AttitudeA": 1,
        "ProbabilityA": 40,
        "AttitudeB": 3,
        "ProbabilityB": 30,
        "AttitudeC": 7,
        "ProbabilityC": 20,
        "AttitudeD": 9,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 2,
        "AttitudeA": 1,
        "ProbabilityA": 40,
        "AttitudeB": 4,
        "ProbabilityB": 30,
        "AttitudeC": 7,
        "ProbabilityC": 20,
        "AttitudeD": 10,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 3,
        "AttitudeA": 1,
        "ProbabilityA": 40,
        "AttitudeB": 5,
        "ProbabilityB": 30,
        "AttitudeC": 7,
        "ProbabilityC": 20,
        "AttitudeD": 11,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 4,
        "AttitudeA": 1,
        "ProbabilityA": 40,
        "AttitudeB": 6,
        "ProbabilityB": 30,
        "AttitudeC": 7,
        "ProbabilityC": 20,
        "AttitudeD": 12,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 5,
        "AttitudeA": 1,
        "ProbabilityA": 40,
        "AttitudeB": 2,
        "ProbabilityB": 30,
        "AttitudeC": 7,
        "ProbabilityC": 20,
        "AttitudeD": 8,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 6,
        "AttitudeA": 2,
        "ProbabilityA": 40,
        "AttitudeB": 3,
        "ProbabilityB": 30,
        "AttitudeC": 8,
        "ProbabilityC": 20,
        "AttitudeD": 9,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 7,
        "AttitudeA": 2,
        "ProbabilityA": 40,
        "AttitudeB": 4,
        "ProbabilityB": 30,
        "AttitudeC": 8,
        "ProbabilityC": 20,
        "AttitudeD": 10,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 8,
        "AttitudeA": 2,
        "ProbabilityA": 40,
        "AttitudeB": 5,
        "ProbabilityB": 30,
        "AttitudeC": 8,
        "ProbabilityC": 20,
        "AttitudeD": 11,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 9,
        "AttitudeA": 2,
        "ProbabilityA": 40,
        "AttitudeB": 6,
        "ProbabilityB": 30,
        "AttitudeC": 8,
        "ProbabilityC": 20,
        "AttitudeD": 12,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 10,
        "AttitudeA": 2,
        "ProbabilityA": 40,
        "AttitudeB": 1,
        "ProbabilityB": 30,
        "AttitudeC": 8,
        "ProbabilityC": 20,
        "AttitudeD": 7,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 11,
        "AttitudeA": 3,
        "ProbabilityA": 40,
        "AttitudeB": 1,
        "ProbabilityB": 30,
        "AttitudeC": 9,
        "ProbabilityC": 20,
        "AttitudeD": 7,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 12,
        "AttitudeA": 3,
        "ProbabilityA": 40,
        "AttitudeB": 2,
        "ProbabilityB": 30,
        "AttitudeC": 9,
        "ProbabilityC": 20,
        "AttitudeD": 8,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 13,
        "AttitudeA": 3,
        "ProbabilityA": 40,
        "AttitudeB": 4,
        "ProbabilityB": 30,
        "AttitudeC": 9,
        "ProbabilityC": 20,
        "AttitudeD": 10,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 14,
        "AttitudeA": 3,
        "ProbabilityA": 40,
        "AttitudeB": 5,
        "ProbabilityB": 30,
        "AttitudeC": 9,
        "ProbabilityC": 20,
        "AttitudeD": 11,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 15,
        "AttitudeA": 3,
        "ProbabilityA": 40,
        "AttitudeB": 6,
        "ProbabilityB": 30,
        "AttitudeC": 9,
        "ProbabilityC": 20,
        "AttitudeD": 12,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 16,
        "AttitudeA": 4,
        "ProbabilityA": 40,
        "AttitudeB": 1,
        "ProbabilityB": 30,
        "AttitudeC": 10,
        "ProbabilityC": 20,
        "AttitudeD": 7,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 17,
        "AttitudeA": 4,
        "ProbabilityA": 40,
        "AttitudeB": 2,
        "ProbabilityB": 30,
        "AttitudeC": 10,
        "ProbabilityC": 20,
        "AttitudeD": 8,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 18,
        "AttitudeA": 4,
        "ProbabilityA": 40,
        "AttitudeB": 3,
        "ProbabilityB": 30,
        "AttitudeC": 10,
        "ProbabilityC": 20,
        "AttitudeD": 9,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 19,
        "AttitudeA": 4,
        "ProbabilityA": 40,
        "AttitudeB": 5,
        "ProbabilityB": 30,
        "AttitudeC": 10,
        "ProbabilityC": 20,
        "AttitudeD": 11,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 20,
        "AttitudeA": 4,
        "ProbabilityA": 40,
        "AttitudeB": 6,
        "ProbabilityB": 30,
        "AttitudeC": 10,
        "ProbabilityC": 20,
        "AttitudeD": 12,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 21,
        "AttitudeA": 5,
        "ProbabilityA": 40,
        "AttitudeB": 1,
        "ProbabilityB": 30,
        "AttitudeC": 11,
        "ProbabilityC": 20,
        "AttitudeD": 7,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 22,
        "AttitudeA": 5,
        "ProbabilityA": 40,
        "AttitudeB": 2,
        "ProbabilityB": 30,
        "AttitudeC": 11,
        "ProbabilityC": 20,
        "AttitudeD": 8,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 23,
        "AttitudeA": 5,
        "ProbabilityA": 40,
        "AttitudeB": 3,
        "ProbabilityB": 30,
        "AttitudeC": 11,
        "ProbabilityC": 20,
        "AttitudeD": 9,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 24,
        "AttitudeA": 5,
        "ProbabilityA": 40,
        "AttitudeB": 4,
        "ProbabilityB": 30,
        "AttitudeC": 11,
        "ProbabilityC": 20,
        "AttitudeD": 10,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 25,
        "AttitudeA": 6,
        "ProbabilityA": 40,
        "AttitudeB": 1,
        "ProbabilityB": 30,
        "AttitudeC": 12,
        "ProbabilityC": 20,
        "AttitudeD": 7,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 26,
        "AttitudeA": 6,
        "ProbabilityA": 40,
        "AttitudeB": 2,
        "ProbabilityB": 30,
        "AttitudeC": 12,
        "ProbabilityC": 20,
        "AttitudeD": 8,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 27,
        "AttitudeA": 6,
        "ProbabilityA": 40,
        "AttitudeB": 3,
        "ProbabilityB": 30,
        "AttitudeC": 12,
        "ProbabilityC": 20,
        "AttitudeD": 9,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 28,
        "AttitudeA": 6,
        "ProbabilityA": 40,
        "AttitudeB": 4,
        "ProbabilityB": 30,
        "AttitudeC": 12,
        "ProbabilityC": 20,
        "AttitudeD": 10,
        "ProbabilityD": 10
    },
    {
        "CharaRandomActType": 29,
        "AttitudeA": 1,
        "ProbabilityA": 100,
        "AttitudeB": 0,
        "ProbabilityB": 0,
        "AttitudeC": 0,
        "ProbabilityC": 0,
        "AttitudeD": 0,
        "ProbabilityD": 0
    },
    {
        "CharaRandomActType": 30,
        "AttitudeA": 7,
        "ProbabilityA": 100,
        "AttitudeB": 0,
        "ProbabilityB": 0,
        "AttitudeC": 0,
        "ProbabilityC": 0,
        "AttitudeD": 0,
        "ProbabilityD": 0
    },
    {
        "CharaRandomActType": 31,
        "AttitudeA": 8,
        "ProbabilityA": 100,
        "AttitudeB": 0,
        "ProbabilityB": 0,
        "AttitudeC": 0,
        "ProbabilityC": 0,
        "AttitudeD": 0,
        "ProbabilityD": 0
    }
]